[advisories]
ignore = [
    "RUSTSEC-2020-0056", # from xml-rs 0.8.4 - unmaintained - it's used in a build script of winit
]

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
